import { markdownToHtml, downloadBlob, generateFilename } from './export-utils';

const CATPPUCCIN_LIGHT = {
  background: '#edd5c5',
  foreground: '#4c4f69',
  primary: '#fe640b',
  muted: '#ccd0da',
  mutedForeground: '#6c6f85',
  card: '#e6e9ef',
  border: '#bcc0cc',
  code: '#e6e9ef',
};

const CATPPUCCIN_DARK = {
  background: '#292c3c',
  foreground: '#cdd6f4',
  primary: '#94e2d5',
  muted: '#313244',
  mutedForeground: '#a6adc8',
  card: '#45475a',
  border: '#585b70',
  code: '#313244',
};

function getStyles(theme: 'light' | 'dark'): string {
  const colors = theme === 'light' ? CATPPUCCIN_LIGHT : CATPPUCCIN_DARK;

  return `
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    
    body {
      font-family: 'General Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.7;
      color: ${colors.foreground};
      background-color: ${colors.background};
      padding: 3rem;
      max-width: 900px;
      margin: 0 auto;
    }
    
    h1, h2, h3, h4, h5, h6 {
      font-family: 'Satoshi', 'General Sans', sans-serif;
      font-weight: 700;
      letter-spacing: -0.025em;
      margin-top: 2rem;
      margin-bottom: 1rem;
      color: ${colors.foreground};
    }
    
    h1 {
      font-size: 2.25rem;
      border-bottom: 2px solid ${colors.primary};
      padding-bottom: 0.5rem;
    }
    
    h2 {
      font-size: 1.75rem;
      color: ${colors.primary};
    }
    
    h3 {
      font-size: 1.375rem;
    }
    
    p {
      margin-bottom: 1rem;
    }
    
    ul, ol {
      margin-bottom: 1rem;
      padding-left: 1.5rem;
    }
    
    li {
      margin-bottom: 0.5rem;
    }
    
    code {
      font-family: 'JetBrains Mono', 'Fira Code', monospace;
      font-size: 0.875em;
      background-color: ${colors.code};
      padding: 0.125rem 0.375rem;
      border-radius: 0.25rem;
    }
    
    pre {
      background-color: ${colors.code};
      padding: 1rem;
      border-radius: 0.5rem;
      overflow-x: auto;
      margin-bottom: 1rem;
    }
    
    pre code {
      background: none;
      padding: 0;
    }
    
    blockquote {
      border-left: 4px solid ${colors.primary};
      padding-left: 1rem;
      margin: 1rem 0;
      color: ${colors.mutedForeground};
      font-style: italic;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 1rem;
    }
    
    th, td {
      border: 1px solid ${colors.border};
      padding: 0.75rem;
      text-align: left;
    }
    
    th {
      background-color: ${colors.muted};
      font-weight: 600;
    }
    
    hr {
      border: none;
      border-top: 1px solid ${colors.border};
      margin: 2rem 0;
    }
    
    a {
      color: ${colors.primary};
      text-decoration: none;
    }
    
    a:hover {
      text-decoration: underline;
    }
    
    .generated-notice {
      font-size: 0.75rem;
      color: ${colors.mutedForeground};
      margin-top: 3rem;
      padding-top: 1rem;
      border-top: 1px solid ${colors.border};
      text-align: center;
    }
  `;
}

function createHtmlDocument(
  content: string,
  title: string,
  theme: 'light' | 'dark'
): string {
  const generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - Planning Document</title>
  <style>${getStyles(theme)}</style>
</head>
<body>
  <article>
    ${content}
  </article>
  <footer class="generated-notice">
    Generated by Agent Advisor on ${generatedDate}
  </footer>
</body>
</html>`;
}

export interface HtmlExportOptions {
  theme?: 'light' | 'dark';
  filename?: string;
}

export async function exportAsHtml(
  markdown: string,
  agentName: string,
  options: HtmlExportOptions = {}
): Promise<void> {
  const { theme = 'light', filename } = options;
  const htmlContent = await markdownToHtml(markdown);
  const fullDocument = createHtmlDocument(htmlContent, agentName, theme);
  const blob = new Blob([fullDocument], { type: 'text/html' });
  const outputFilename = filename ?? generateFilename(agentName, 'html');
  downloadBlob(blob, outputFilename);
}

export async function generateHtmlString(
  markdown: string,
  agentName: string,
  theme: 'light' | 'dark' = 'light'
): Promise<string> {
  const htmlContent = await markdownToHtml(markdown);
  return createHtmlDocument(htmlContent, agentName, theme);
}
